rocketfire_agence_main:
    resource: "@RocketfireAgenceMainBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    path: /Login/logout

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
