<?php

namespace RocketfireAgenceMainBundle\Repository;

/**
 * AeroportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AeroportRepository extends \Doctrine\ORM\EntityRepository
{
}
