<?php

namespace RocketfireAgenceMainBundle\Repository;

/**
 * CompagnieAerienneVolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompagnieAerienneVolRepository extends \Doctrine\ORM\EntityRepository
{
}
