<?php

namespace RocketfireAgenceMainBundle\Repository;

/**
 * CompagnieAerienneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompagnieAerienneRepository extends \Doctrine\ORM\EntityRepository
{
}
