<?php

namespace RocketfireAgenceMainBundle\Repository;

/**
 * EscaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscaleRepository extends \Doctrine\ORM\EntityRepository
{
}
