<?php

namespace RocketfireAgenceMainBundle\Repository;

/**
 * PassagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassagerRepository extends \Doctrine\ORM\EntityRepository
{
}
