<?php

namespace RocketfireAgenceMainBundle\Repository;

/**
 * Ville_AeroportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ville_AeroportRepository extends \Doctrine\ORM\EntityRepository
{
}
