<?php

namespace RocketfireAgenceMainBundle\Repository;

/**
 * VilleAeroportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleAeroportRepository extends \Doctrine\ORM\EntityRepository
{
}
