<?php

namespace RocketfireAgenceMainBundle\Repository;

/**
 * VolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VolRepository extends \Doctrine\ORM\EntityRepository
{
}
